### ISSUE TITLE
500 error while using deploy-to-neocities

### ISSUE THREAD

**Issue by victoriadrake** [bcomnes/async-neocities#18] opened 2021-01-03 21:16 UTC
I ran into this while using the https://github.com/bcomnes/deploy-to-neocities GitHub action, but I open this issue here as I believe it's actually coming from async-neocities.

```
Run bcomnes/deploy-to-neocities@v1
Starting inspecting stage...
Finished inspecting stage.
Starting diffing stage...
Finished diffing stage.
Starting applying stage...
Stage applying: 0.00% (0 B / 1.02 MB)
Stage applying: 17.82% (181 kB / 1.02 MB)
Stage applying: 100.00% (1.02 MB / 1.02 MB)
TextHTTPError: Internal Server Error
    at handleResponse (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/node_modules/fetch-errors/index.js:9:1)
Error: Internal Server Error
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/node_modules/async-neocities/index.js:286:1)
    at doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/index.js:20:1) {
  name: 'TextHTTPError',
  status: 500,
  data: 'An unhandled lowlevel error occurred. The application logs may have details.\n'
}
```

My site does successfully render and I can deploy it using the Neocities CLI locally, so I doubt it's a syntax error in my site files. I'm afraid I haven't got more info than the logs above. I hope it helps!

**Comment by bcomnes** [comment] 2021-01-03 21:45
Thanks for bringing this to my attention.  Looks like deploy-to-neocities is getting a 500 error from the Neocities API.  Some combination of the files you are trying to upload and how async-neocities is doing that is probably making the API unhappy.    

My best guess is that a file type, file name or large file isn't getting filtered out from the list of file to upload, and the API is rejecting it with a nondescript error message. Do any files in your site fit those qualifications?  Have you been able to pinpoint which file is causing this?  Do you have an open source repo for the site that is having issues that I could take a look at?

@kyledrake is there any way to get any info on why something is being rejected behind a 500 error?

**Comment by bcomnes** [comment] 2021-01-03 22:21
Also, just looking at the failure mode here, I'm thinking that async-neocities should handle this error better, and return a better wrapped error that includes things like file names.

**Comment by bcomnes** [comment] 2021-01-03 22:51
Ok, I just made a new release of deploy-to-neocities.  It probably won't fix your problem, but it will dump a list of files that its trying to upload (or delete), which should help pinpoint the file giving us trouble.

https://github.com/bcomnes/deploy-to-neocities/releases/tag/v1.0.15

If you can try that out, get me the output of that failing step, it should hopefully make it clear where the issue is.

**Comment by bcomnes** [comment] 2021-01-06 16:53
> In trying this tag out I also realized that my first run was with deploy-to-neocities@v1, which I copied from the README. This behavior still occurs with the new tags, however.

Ah yeah I'll fix that. 

> I gave it a couple tries. The files I was attempting to upload are the contents of this folder. I suspect that some timeout is occurring because there are many files.

Getting a 404 on that link.  But large numbers of files might be the case.  I'm using a single http request and piping all files through a multipart form, but at a certain point I wonder if neckties just gives up after a timeout our size.  I might have to add some batching to uploads.  

If you don't mind, could you throw a snapshot of the tree you were referencing back up on a branch so I can grab a copy of something that is triggering the issue?  That would help me debug.

**Comment by victoriadrake** [comment] 2021-01-08 12:30
Whoops. Here's the [right link](https://github.com/victoriadrake/victoriadrake.github.io/tree/master/neofeed). This is the built content and uploading this folder seems to trigger the issue.

By the way, I'm incorporating the action in [this new project](https://github.com/victoriadrake/neocities-neofeed), if you're curious! 😄

**Comment by bcomnes** [comment] 2021-01-08 15:51
> Whoops. Here's the right link. This is the built content and uploading this folder seems to trigger the issue.

Cool, grabbing a copy.  If you don't mind, I might temporarily upload this to a throwaway Neocities site to diagnose the issue myself (and have something to test out). 

> By the way, I'm incorporating the action in this new project, if you're curious! 😄

@victoriadrake that's awesome!  Feel free to add a link to the project on the README so others can reference your integration:

**Comment by victoriadrake** [comment] 2021-01-12 23:58
Absolutely! And thanks again for following up.

**Comment by bcomnes** [comment] 2021-01-17 17:19
Ok, I've recreated the issue, and indeed, large number of files in a single upload stream causes neocities to choke. 

I've come up with a batch post method that chunks upload requests into batches of 50 files at a time.  I might need to tune that a bit but its working on your site, so it's probably a good place to start.   I'll close this issue out once I get that done and deployed.

**Closed** 2021-01-17 17:55 UTC

**Comment by bcomnes** [comment] 2021-01-17 18:19
Ok, deploy-to-neocities us now using the batching strategy on v1.0.17 (or v1).  You should be able to deploy large site with lots of files now!  Thanks for stress testing this, I hadn't attempted large sets of file in my own use case yet.
